<div id= "socialbar" class="a2a_kit a2a_kit_size_32 a2a_floating_style a2a_vertical_style">
<a class="a2a_dd" href="https://www.addtoany.com/share" rel="nofollow"></a>
<a class="a2a_button_facebook" rel="nofollow"></a>
<a class="a2a_button_twitter" rel="nofollow"></a>
<a class="a2a_button_linkedin" rel="nofollow"></a>
</div>

Home
===================================== 

Row
-----------------------------------------------------------------------


### Confirmed

```{r}
valueBox(comma(n_total$confirmed), caption = "Total Confirmed", icon = "fa-check", 
         color="#222")
```

### Active

```{r}
valueBox(comma(n_total$active_cases), 
         caption = "Active Cases", icon = "fa-procedures", color="#222")
```

### Recovered

```{r}
valueBox(comma(n_total$recovered), caption = "Total Recovered", icon = "fa-heart", 
         color="#222")
```

### Deaths

```{r}
valueBox(comma(n_total$deaths), caption = "Total Deaths", icon = "fa-skull", 
         color="#222")
```

### Countries

```{r}
valueBox(nrow(tbl_df), caption = "Countries Affected", icon = "fa-flag", 
         color="#222")
```

Row 
-----------------------------------------------------------------------


### Global Spread of Corona Virus - `r Sys.Date() - 1` 

```{r}
map_corona
```

### Corona Virus Spread by Number - `r Sys.Date() - 1` {data-width=250}

```{r}
names(tbl_df) <- c("Country", "Confirmed", "Deaths", "Recovered")

kable(tbl_df) %>% kableExtra::kable_styling("striped", full_width = T) 
```